#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("OTD.Resource", IsApplication=true)]

namespace OTD
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int remotegray = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int remotegreen = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int remoteorange = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int remotered = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int remotewhite = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050001
			public const int EntryPassWiFi = 2131034113;
			
			// aapt resource value: 0x7f05000b
			public const int LaBelSSID = 2131034123;
			
			// aapt resource value: 0x7f050000
			public const int LabelPassWiFi = 2131034112;
			
			// aapt resource value: 0x7f05000f
			public const int LabelWiFi = 2131034127;
			
			// aapt resource value: 0x7f05000c
			public const int OpenDoorButton = 2131034124;
			
			// aapt resource value: 0x7f050010
			public const int WiFiListView = 2131034128;
			
			// aapt resource value: 0x7f05000a
			public const int WiFiListView2 = 2131034122;
			
			// aapt resource value: 0x7f05000d
			public const int btnConfig = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int btnExit = 2131034126;
			
			// aapt resource value: 0x7f050008
			public const int btnSave = 2131034120;
			
			// aapt resource value: 0x7f050003
			public const int entryCodDoor = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int entryUrlDoor = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int lblCodeDoor = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int lblUrlDoor = 2131034116;
			
			// aapt resource value: 0x7f050009
			public const int lblWiFiList = 2131034121;
			
			// aapt resource value: 0x7f050006
			public const int lblWiFiToUse = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int lblWiFiToUseSelected = 2131034119;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Configuracion = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int LabelWiFi = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int Title = 2130968578;
			
			// aapt resource value: 0x7f040005
			public const int lblCodeDoor = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int lblPassWiFi = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int lblUrlDoor = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int lblWiFiList = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int lblWiFiToUse = 2130968584;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
